#!/usr/bin/env python3
"""Sanitize generated China DIRECT rules before regression/publish.

Safety model:
- China source contributes DOMAIN / DOMAIN-SUFFIX only.
- IP-CIDR/IP-CIDR6/DOMAIN-KEYWORD and other match types are excluded from the
  China DIRECT ruleset; explicit destination-IP routing is handled by
  GEOIP,CN,no-resolve in the user's Shadowrocket config.
- Domains covered by any higher-priority non-China proxy category are removed
  from the China DIRECT set.
- Public non-CN TLDs are excluded using the maintained Loyalsoldier tld-not-cn
  list; failures to download it do not silently expand the China allowlist.
- A small explicit foreign-domain denylist covers known regression cases whose
  TLD is globally shared (.com/.net).
"""
from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "rules"
REPORTS = ROOT / "reports"
CHINA_ATOMIC = RULES / "atomic" / "china" / "domains.list"
CHINA_COMPILED = RULES / "compiled" / "china.list"
TLD_URL = "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"

# Explicitly verified foreign/global domains that must never be China DIRECT.
# Keep this conservative: these are regression fixtures, not a broad brand list.
EXPLICIT_DENY = {
    "nvidia.net",
    "developer.microsoft.com",
    "google.com",
    "github.com",
    "openai.com",
    "steamcommunity.com",
    "1e100.net",
    "np-edge.itunes.apple.com",
    "play-edge.itunes.apple.com",
}

ALLOW_TYPES = {"DOMAIN", "DOMAIN-SUFFIX"}


def normalize_domain(value: str) -> str:
    return value.strip().lower().rstrip(".")


def domain_matches(rule: str, domain: str) -> bool:
    try:
        kind, value = rule.split(",", 1)
    except ValueError:
        return False
    value = normalize_domain(value)
    domain = normalize_domain(domain)
    if kind == "DOMAIN":
        return domain == value
    if kind == "DOMAIN-SUFFIX":
        return domain == value or domain.endswith("." + value)
    return False


def rule_value(rule: str) -> tuple[str, str] | None:
    parts = rule.split(",", 1)
    if len(parts) != 2:
        return None
    return parts[0].strip().upper(), normalize_domain(parts[1])


def load_tld_exclusions() -> set[str]:
    req = urllib.request.Request(TLD_URL, headers={"User-Agent": "Group-Rule/10.0"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            text = resp.read(1024 * 1024).decode("utf-8", "replace")
    except Exception as exc:
        raise RuntimeError(f"tld_exclusion_unavailable: {exc}") from exc
    result = set()
    for line in text.splitlines():
        match = re.search(r"['\"]\+\.(.+?)['\"]", line.strip())
        if match:
            result.add(match.group(1).lower().rstrip("."))
    if not result:
        raise RuntimeError("tld_exclusion_empty")
    return result


def load_proxy_domain_rules() -> list[str]:
    rules: list[str] = []
    for category in ("ai", "streaming", "social", "developer", "service", "global"):
        path = RULES / "compiled" / f"{category}.list"
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            value = rule_value(line.strip()) if line.strip() and not line.lstrip().startswith("#") else None
            if value and value[0] in ALLOW_TYPES:
                rules.append(f"{value[0]},{value[1]}")
    return rules


def filter_china_rules(rules: list[str], proxy_rules: list[str], excluded_tlds: set[str]):
    kept: list[str] = []
    reasons = {"non_domain": 0, "foreign_tld": 0, "explicit_deny": 0, "proxy_category_overlap": 0, "invalid": 0}
    for raw in rules:
        parsed = rule_value(raw)
        if not parsed:
            reasons["invalid"] += 1
            continue
        kind, value = parsed
        if kind not in ALLOW_TYPES:
            reasons["non_domain"] += 1
            continue
        if not value or "." not in value:
            reasons["invalid"] += 1
            continue
        if value in EXPLICIT_DENY or any(value == d or value.endswith("." + d) for d in EXPLICIT_DENY):
            reasons["explicit_deny"] += 1
            continue
        tld = value.rsplit(".", 1)[-1]
        if tld in excluded_tlds:
            reasons["foreign_tld"] += 1
            continue
        if any(domain_matches(proxy_rule, value) or domain_matches(raw, proxy_rule.split(",", 1)[1]) for proxy_rule in proxy_rules):
            reasons["proxy_category_overlap"] += 1
            continue
        kept.append(f"{kind},{value}")
    return list(dict.fromkeys(kept)), reasons


def write_rules(path: Path, rules: list[str], kind: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Generated by thunder0775/Group-Rule",
        f"# Type: {kind}",
        "# Policy intentionally omitted; assign DIRECT in Shadowrocket .conf.",
        "# Sanitized: domain-only; foreign/high-risk overlaps removed.",
    ]
    path.write_text("\n".join(header + rules) + "\n", encoding="utf-8")


def update_report(stats):
    json_path = REPORTS / "latest.json"
    if json_path.exists():
        try:
            report = json.loads(json_path.read_text(encoding="utf-8"))
            report["direct_sanitization"] = stats
            json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        except Exception:
            pass
    md_path = REPORTS / "latest.md"
    if md_path.exists():
        md = md_path.read_text(encoding="utf-8")
        block = [
            "",
            "## 中国直连安全过滤",
            "",
            f"- 原始中国规则：`{stats['input_rules']}`",
            f"- 发布中国域名规则：`{stats['output_rules']}`",
            f"- 移除非域名/IP/关键词规则：`{stats['removed']['non_domain']}`",
            f"- 移除非 CN TLD：`{stats['removed']['foreign_tld']}`",
            f"- 移除显式海外回归域名：`{stats['removed']['explicit_deny']}`",
            f"- 移除与海外高优先级分类重叠：`{stats['removed']['proxy_category_overlap']}`",
        ]
        md_path.write_text(md.rstrip() + "\n" + "\n".join(block) + "\n", encoding="utf-8")


def main() -> int:
    if not CHINA_ATOMIC.exists():
        print("DIRECT RULE SANITIZE: BLOCK")
        print(f"- missing input: {CHINA_ATOMIC}")
        return 1
    raw_rules = [
        line.strip()
        for line in CHINA_ATOMIC.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    try:
        tlds = load_tld_exclusions()
        proxy_rules = load_proxy_domain_rules()
        safe_rules, reasons = filter_china_rules(raw_rules, proxy_rules, tlds)
    except RuntimeError as exc:
        print("DIRECT RULE SANITIZE: BLOCK")
        print(f"- {exc}")
        return 1

    if not safe_rules:
        print("DIRECT RULE SANITIZE: BLOCK")
        print("- sanitized China domain set is empty")
        return 1

    write_rules(CHINA_ATOMIC, safe_rules, "atomic:china/domains:sanitized")
    write_rules(CHINA_COMPILED, safe_rules, "compiled:china:sanitized")

    stats = {
        "input_rules": len(raw_rules),
        "output_rules": len(safe_rules),
        "removed": reasons,
        "explicit_deny_count": len(EXPLICIT_DENY),
        "proxy_domain_evidence_rules": len(proxy_rules),
        "foreign_tld_count": len(tlds),
    }
    update_report(stats)
    print("DIRECT RULE SANITIZE: PASS")
    print(json.dumps(stats, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
