#!/usr/bin/env python3
"""Sanitize generated China DIRECT rules before regression/publish."""
from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "rules"
REPORTS = ROOT / "reports"
CHINA_ATOMIC = RULES / "atomic" / "china" / "domains.list"
CHINA_COMPILED = RULES / "compiled" / "china.list"
TLD_URL = "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"

EXPLICIT_DENY = {
    "nvidia.net",
    "developer.microsoft.com",
    "google.com",
    "github.com",
    "openai.com",
    "steamcommunity.com",
    "1e100.net",
    "np-edge.itunes.apple.com",
    "play-edge.itunes.apple.com",
}
ALLOW_TYPES = {"DOMAIN", "DOMAIN-SUFFIX"}
PROXY_CATEGORIES = ("ai", "streaming", "social", "developer", "service", "global")


def normalize_domain(value: str) -> str:
    return value.strip().lower().rstrip(".")


def rule_value(rule: str) -> tuple[str, str] | None:
    parts = rule.split(",", 1)
    if len(parts) != 2:
        return None
    return parts[0].strip().upper(), normalize_domain(parts[1])


def domain_covered(kind: str, value: str, exact: set[str], suffixes: set[str]) -> bool:
    if kind == "DOMAIN" and value in exact:
        return True
    labels = value.split(".")
    for index in range(len(labels)):
        parent = ".".join(labels[index:])
        if parent in suffixes:
            return True
    return False


def load_tld_exclusions() -> set[str]:
    req = urllib.request.Request(TLD_URL, headers={"User-Agent": "Group-Rule/10.1"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            text = resp.read(1024 * 1024).decode("utf-8", "replace")
    except Exception as exc:
        raise RuntimeError(f"tld_exclusion_unavailable: {exc}") from exc
    result = set()
    for line in text.splitlines():
        match = re.search(r"['\"]\+\.(.+?)['\"]", line.strip())
        if match:
            result.add(match.group(1).lower().rstrip("."))
    if not result:
        raise RuntimeError("tld_exclusion_empty")
    return result


def load_proxy_domain_index() -> tuple[set[str], set[str], int]:
    exact, suffixes, count = set(), set(), 0
    for category in PROXY_CATEGORIES:
        path = RULES / "compiled" / f"{category}.list"
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            parsed = rule_value(line.strip()) if line.strip() and not line.lstrip().startswith("#") else None
            if not parsed or parsed[0] not in ALLOW_TYPES:
                continue
            count += 1
            if parsed[0] == "DOMAIN":
                exact.add(parsed[1])
            else:
                suffixes.add(parsed[1])
    return exact, suffixes, count


def filter_china_rules(rules: list[str], proxy_exact: set[str], proxy_suffixes: set[str], excluded_tlds: set[str]):
    kept = []
    reasons = {"non_domain": 0, "foreign_tld": 0, "explicit_deny": 0, "proxy_category_overlap": 0, "invalid": 0}
    for raw in rules:
        parsed = rule_value(raw)
        if not parsed:
            reasons["invalid"] += 1
            continue
        kind, value = parsed
        if kind not in ALLOW_TYPES:
            reasons["non_domain"] += 1
            continue
        if not value or "." not in value:
            reasons["invalid"] += 1
            continue
        if value in EXPLICIT_DENY or any(value == d or value.endswith("." + d) for d in EXPLICIT_DENY):
            reasons["explicit_deny"] += 1
            continue
        tld = value.rsplit(".", 1)[-1]
        if tld in excluded_tlds:
            reasons["foreign_tld"] += 1
            continue
        if domain_covered(kind, value, proxy_exact, proxy_suffixes):
            reasons["proxy_category_overlap"] += 1
            continue
        kept.append(f"{kind},{value}")
    return list(dict.fromkeys(kept)), reasons


def write_rules(path: Path, rules: list[str], kind: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Generated by thunder0775/Group-Rule",
        f"# Type: {kind}",
        "# Policy intentionally omitted; assign DIRECT in Shadowrocket .conf.",
        "# Sanitized: domain-only; foreign/high-risk overlaps removed.",
    ]
    path.write_text("\n".join(header + rules) + "\n", encoding="utf-8")


def update_report(stats):
    json_path = REPORTS / "latest.json"
    if json_path.exists():
        try:
            report = json.loads(json_path.read_text(encoding="utf-8"))
            report["direct_sanitization"] = stats
            json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        except Exception:
            pass
    md_path = REPORTS / "latest.md"
    if md_path.exists():
        md = md_path.read_text(encoding="utf-8").rstrip()
        block = [
            "",
            "## 中国直连安全过滤",
            "",
            f"- 原始中国规则：`{stats['input_rules']}`",
            f"- 发布中国域名规则：`{stats['output_rules']}`",
            f"- 移除非域名/关键词/IP规则：`{stats['removed']['non_domain']}`",
            f"- 移除非 CN TLD：`{stats['removed']['foreign_tld']}`",
            f"- 移除显式海外回归域名：`{stats['removed']['explicit_deny']}`",
            f"- 移除与海外高优先级分类重叠：`{stats['removed']['proxy_category_overlap']}`",
        ]
        md_path.write_text(md + "\n" + "\n".join(block) + "\n", encoding="utf-8")


def main() -> int:
    if not CHINA_ATOMIC.exists():
        print("DIRECT RULE SANITIZE: BLOCK")
        print(f"- missing input: {CHINA_ATOMIC}")
        return 1
    raw_rules = [
        line.strip()
        for line in CHINA_ATOMIC.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    try:
        tlds = load_tld_exclusions()
        exact, suffixes, proxy_count = load_proxy_domain_index()
        safe_rules, reasons = filter_china_rules(raw_rules, exact, suffixes, tlds)
    except RuntimeError as exc:
        print("DIRECT RULE SANITIZE: BLOCK")
        print(f"- {exc}")
        return 1

    if not safe_rules:
        print("DIRECT RULE SANITIZE: BLOCK")
        print("- sanitized China domain set is empty")
        return 1

    write_rules(CHINA_ATOMIC, safe_rules, "atomic:china/domains:sanitized")
    write_rules(CHINA_COMPILED, safe_rules, "compiled:china:sanitized")

    stats = {
        "input_rules": len(raw_rules),
        "output_rules": len(safe_rules),
        "removed": reasons,
        "explicit_deny_count": len(EXPLICIT_DENY),
        "proxy_domain_evidence_rules": proxy_count,
        "foreign_tld_count": len(tlds),
    }
    update_report(stats)
    print("DIRECT RULE SANITIZE: PASS")
    print(json.dumps(stats, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
