#!/usr/bin/env python3
"""Fetch, validate, isolate, deduplicate and compile Shadowrocket rules."""
from __future__ import annotations
import hashlib, json, re, sys, urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / "config"
RULES = ROOT / "rules"
REPORTS = ROOT / "reports"
ALLOWED = {"DOMAIN", "DOMAIN-SUFFIX", "DOMAIN-KEYWORD", "IP-CIDR", "IP-CIDR6", "USER-AGENT", "URL-REGEX", "PROCESS-NAME", "DEST-PORT", "DST-PORT", "GEOIP"}

def now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()

def load(path):
    return json.loads(path.read_text(encoding="utf-8"))

def norm(line):
    line = line.replace("\ufeff", "").strip()
    if not line or line.startswith("#") or line.startswith(";"):
        return None
    p = [x.strip() for x in line.split(",")]
    if len(p) < 2 or p[0] not in ALLOWED or not p[1]:
        return None
    # IMPORTANT: discard policy/options. Generated rules are policy-free.
    return f"{p[0]},{p[1]}"

def parse(text):
    out, seen = [], set()
    for line in text.splitlines():
        r = norm(line)
        if r and r not in seen:
            seen.add(r); out.append(r)
    return out

def fetch(url, timeout, max_bytes):
    req = urllib.request.Request(url, headers={"User-Agent": "Group-Rule/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        data = resp.read(max_bytes + 1)
        if len(data) > max_bytes:
            raise ValueError("response_too_large")
        text = data.decode("utf-8-sig")
        return text, {"status_code": getattr(resp, "status", 200), "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(), "final_url": resp.geturl()}

def valid_payload(text, rules):
    low = text.lower()
    if "<html" in low or "<!doctype html" in low:
        return "html_instead_of_rules"
    if not rules:
        return "zero_rules"
    return None

def path_for(category, name):
    return RULES / "atomic" / category / f"{name}.list"

def read_previous(path):
    return parse(path.read_text(encoding="utf-8")) if path.exists() else []

def write_list(path, rules, kind):
    path.parent.mkdir(parents=True, exist_ok=True)
    header = ["# Generated by thunder0775/Group-Rule", f"# Type: {kind}", f"# Generated: {now()}", "# Policy intentionally omitted; assign policy in Shadowrocket .conf."]
    path.write_text("\n".join(header + list(dict.fromkeys(rules))) + "\n", encoding="utf-8")

def main():
    scfg = load(CFG / "sources.json")
    pcfg = load(CFG / "priority.json")
    timeout = int(scfg.get("source_timeout", 30))
    max_bytes = int(scfg.get("max_bytes", 5 * 1024 * 1024))
    statuses = {}
    categories = defaultdict(dict)

    for category, items in scfg["sources"].items():
        for name, urls in items.items():
            target = path_for(category, name)
            previous = read_previous(target)
            candidates = []
            source_results = []
            good = False
            for url in urls:
                try:
                    text, meta = fetch(url, timeout, max_bytes)
                    parsed = parse(text)
                    reason = valid_payload(text, parsed)
                    ok = reason is None
                    item = {"url": url, **meta, "rules": len(parsed), "status": "ok" if ok else "rejected"}
                    if reason: item["reason"] = reason
                    if ok:
                        candidates.extend(parsed); good = True
                except Exception as exc:
                    item = {"url": url, "status": "error", "error": str(exc)}
                source_results.append(item)

            custom = scfg.get("custom", {}).get(f"{category}/{name}.list", [])
            candidates.extend(x for x in map(norm, custom) if x)
            candidates = list(dict.fromkeys(candidates))

            if candidates and (good or custom):
                write_list(target, candidates, f"atomic:{category}/{name}")
                current, state = candidates, "updated"
            else:
                current, state = previous, "kept_previous" if previous else "unavailable"
                if previous:
                    write_list(target, previous, f"atomic:{category}/{name}:last-known-good")
            categories[category][name] = current
            statuses[f"{category}/{name}"] = {"state": state, "rule_count": len(current), "previous_count": len(previous), "sources": source_results}

    # Compile by category, still without policies.
    compiled = {}
    for category, items in categories.items():
        merged = list(dict.fromkeys(r for rules in items.values() for r in rules))
        write_list(RULES / "compiled" / f"{category}.list", merged, f"compiled:{category}")
        compiled[category] = len(merged)

    # Exact-rule overlap across categories. The conflict policy is defined in priority.json;
    # we report every overlap rather than silently deleting anything.
    occurrences = defaultdict(set)
    for category, items in categories.items():
        for name, rules in items.items():
            for r in rules:
                occurrences[r].add(category)
    conflicts = {r: sorted(cats) for r, cats in occurrences.items() if len(cats) > 1}

    REPORTS.mkdir(parents=True, exist_ok=True)
    report = {"generated_at": now(), "status": statuses, "compiled_counts": compiled, "cross_category_conflicts": conflicts, "priority": pcfg}
    (REPORTS / "latest.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    md = ["# Group-Rule 审计报告", "", f"生成时间：`{report['generated_at']}`", f"跨分类重复规则：`{len(conflicts)}`", "", "## 分类统计", ""]
    md += [f"- `{k}`：{v} 条" for k, v in compiled.items()]
    md += ["", "## 原子规则状态", ""]
    for key, st in sorted(statuses.items()):
        md.append(f"- `{key}`：**{st['state']}**，当前 {st['rule_count']}，历史 {st['previous_count']}")
        for src in st["sources"]:
            if src.get("status") != "ok":
                md.append(f"  - ⚠️ `{src.get('url')}` → `{src.get('status')}` {src.get('reason', src.get('error', ''))}")
    if conflicts:
        md += ["", "## 冲突示例（最多 100 条）", ""]
        md += [f"- `{r}` → {', '.join(c)}" for r, c in list(sorted(conflicts.items()))[:100]]
    (REPORTS / "latest.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print(json.dumps({"ok": True, "conflicts": len(conflicts), "compiled": compiled}, ensure_ascii=False))

if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"FATAL: {exc}", file=sys.stderr)
        raise
