#!/usr/bin/env python3
"""Fetch, validate, isolate, deduplicate and compile Shadowrocket rules."""
from __future__ import annotations
import hashlib, json, urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CFG, RULES, REPORTS = ROOT / "config", ROOT / "rules", ROOT / "reports"
ALLOWED = {"DOMAIN","DOMAIN-SUFFIX","DOMAIN-KEYWORD","IP-CIDR","IP-CIDR6","USER-AGENT","URL-REGEX","PROCESS-NAME","DEST-PORT","DST-PORT","GEOIP"}


def now(): return datetime.now(timezone.utc).replace(microsecond=0).isoformat()
def load(p): return json.loads(p.read_text(encoding="utf-8"))


def norm(line):
    line=line.replace("\ufeff","").strip()
    if not line or line.startswith(("#",";")): return None
    p=[x.strip() for x in line.split(",")]
    if len(p)<2 or p[0] not in ALLOWED or not p[1]: return None
    return f"{p[0]},{p[1]}"


def parse(text, mode="rules", expected_policy=None):
    out=[]; seen=set(); in_rule = mode != "shadowrocket_conf"
    for line in text.splitlines():
        s=line.replace("\ufeff","").strip()
        if not s: continue
        if mode == "shadowrocket_conf" and s.startswith("[") and s.endswith("]"):
            in_rule = s.lower() == "[rule]"; continue
        if mode == "domains":
            r=None if not s or s.startswith(("#",";")) or "," in s else f"DOMAIN-SUFFIX,{s}"
        else:
            if mode == "shadowrocket_conf" and not in_rule: continue
            p=[x.strip() for x in s.split(",")]
            if expected_policy is not None:
                if len(p)<3 or p[2].upper() != expected_policy.upper(): continue
            r=norm(s)
        if r and r not in seen: seen.add(r); out.append(r)
    return out


def source_line_stats(text, mode):
    considered = 0
    malformed = 0
    in_rule = mode != "shadowrocket_conf"
    for line in text.splitlines():
        s=line.replace("\ufeff","").strip()
        if not s: continue
        if mode == "shadowrocket_conf" and s.startswith("[") and s.endswith("]"):
            in_rule = s.lower() == "[rule]"
            continue
        if mode == "shadowrocket_conf" and not in_rule: continue
        if s.startswith(("#",";")): continue
        considered += 1
        if mode == "domains":
            if "," in s: malformed += 1
        elif norm(s) is None:
            malformed += 1
    return considered, malformed


def fetch(url, timeout, max_bytes):
    req=urllib.request.Request(url,headers={"User-Agent":"Group-Rule/2.0"})
    with urllib.request.urlopen(req,timeout=timeout) as resp:
        data=resp.read(max_bytes+1)
        if len(data)>max_bytes: raise ValueError("response_too_large")
        return data.decode("utf-8-sig"), {"status_code":getattr(resp,"status",200),"bytes":len(data),"sha256":hashlib.sha256(data).hexdigest(),"final_url":resp.geturl()}


def valid(text,rules,min_rules=1,previous_source_rules=0,min_rule_ratio=0.2,max_rule_ratio=10.0,max_invalid_ratio=0.8,mode="rules"):
    low=text.lower()
    if "<html" in low or "<!doctype html" in low: return "html_instead_of_rules"
    if len(rules) < min_rules: return "too_few_rules"
    if previous_source_rules >= 10 and len(rules) < int(previous_source_rules * min_rule_ratio): return "sudden_rule_count_drop"
    if previous_source_rules >= 10 and len(rules) > int(previous_source_rules * max_rule_ratio): return "sudden_rule_count_growth"
    considered, malformed = source_line_stats(text, mode)
    if considered >= 10 and malformed / considered > max_invalid_ratio: return "high_invalid_rule_ratio"
    return None


def atomic_path(c,n): return RULES/"atomic"/c/f"{n}.list"
def read_previous(p): return parse(p.read_text(encoding="utf-8")) if p.exists() else []
def read_source_history():
    p=REPORTS/"latest.json"
    if not p.exists(): return {}
    try: report=load(p)
    except Exception: return {}
    history={}
    for st in report.get("status",{}).values():
        for src in st.get("sources",[]):
            url=src.get("url")
            if url: history[url]=int(src.get("rules",0))
    return history


def write_list(p,rules,kind):
    p.parent.mkdir(parents=True,exist_ok=True)
    header=["# Generated by thunder0775/Group-Rule",f"# Type: {kind}",f"# Generated: {now()}","# Policy intentionally omitted; assign policy in Shadowrocket .conf."]
    p.write_text("\n".join(header+list(dict.fromkeys(rules)))+"\n",encoding="utf-8")


def semantic_domain_redundancy(categories):
    """Audit DOMAIN/DOMAIN-SUFFIX containment without modifying compiled output."""
    domain_map=defaultdict(list)
    suffix_map=defaultdict(list)
    for category,items in categories.items():
        for name,rules in items.items():
            for rule in rules:
                kind, value = rule.split(",",1)
                value=value.lower().rstrip(".")
                if kind == "DOMAIN": domain_map[value].append({"category":category,"item":name,"rule":rule})
                elif kind == "DOMAIN-SUFFIX": suffix_map[value].append({"category":category,"item":name,"rule":rule})

    findings=[]
    # A suffix rule makes deeper child suffix rules redundant.
    suffixes=sorted(suffix_map, key=lambda x:(x.count("."),x))
    for child in suffixes:
        labels=child.split(".")
        parents=[".".join(labels[i:]) for i in range(1,len(labels))]
        for parent in parents:
            if parent in suffix_map:
                for child_ref in suffix_map[child]:
                    for parent_ref in suffix_map[parent]:
                        findings.append({"type":"parent_suffix_covers_child_suffix","covered":child_ref,"covering":parent_ref})
                break

    # DOMAIN exact match covered by a suffix rule.
    for domain, domain_refs in domain_map.items():
        labels=domain.split(".")
        for i in range(len(labels)):
            suffix=".".join(labels[i:])
            if suffix in suffix_map:
                for domain_ref in domain_refs:
                    for suffix_ref in suffix_map[suffix]:
                        findings.append({"type":"suffix_covers_exact_domain","covered":domain_ref,"covering":suffix_ref})
                break

    # Same semantic rule repeated inside one or multiple atomic files.
    return findings


def main():
    scfg=load(CFG/"sources.json"); pcfg=load(CFG/"priority.json")
    timeout=int(scfg.get("source_timeout",30)); max_bytes=int(scfg.get("max_bytes",10*1024*1024))
    health=scfg.get("health",{}); min_rules_default=int(health.get("min_rules",1)); min_ratio=float(health.get("min_rule_ratio",0.2)); max_ratio=float(health.get("max_rule_ratio",10.0)); max_invalid_ratio=float(health.get("max_invalid_ratio",0.8))
    source_history=read_source_history()
    statuses={}; categories=defaultdict(dict)
    for category,items in scfg["sources"].items():
        for name,sources in items.items():
            target=atomic_path(category,name); previous=read_previous(target)
            candidates=[]; results=[]; healthy=0
            for src in sources:
                if isinstance(src,str): src={"url":src}
                url=src["url"]; mode=src.get("mode","rules"); policy=src.get("policy")
                min_rules=int(src.get("min_rules",min_rules_default)); ratio=float(src.get("min_rule_ratio",min_ratio)); max_source_ratio=float(src.get("max_rule_ratio",max_ratio)); invalid_ratio=float(src.get("max_invalid_ratio",max_invalid_ratio))
                previous_source_rules=source_history.get(url,0)
                try:
                    text,meta=fetch(url,timeout,max_bytes); parsed=parse(text,mode,policy); considered,malformed=source_line_stats(text,mode); reason=valid(text,parsed,min_rules,previous_source_rules,ratio,max_source_ratio,invalid_ratio,mode)
                    ok=reason is None; item={"url":url,"mode":mode,"policy_filter":policy,"min_rules":min_rules,"previous_source_rules":previous_source_rules,"considered_lines":considered,"malformed_lines":malformed,"max_invalid_ratio":invalid_ratio,**meta,"rules":len(parsed),"status":"ok" if ok else "rejected"}
                    if reason: item["reason"]=reason
                    if ok: candidates.extend(parsed); healthy+=1
                except Exception as exc: item={"url":url,"mode":mode,"policy_filter":policy,"min_rules":min_rules,"previous_source_rules":previous_source_rules,"status":"error","error":str(exc)}
                results.append(item)
            custom=[norm(x) for x in scfg.get("custom",{}).get(f"{category}/{name}.list",[])]; custom=[x for x in custom if x]
            candidates=list(dict.fromkeys(candidates+custom))
            if candidates and (healthy>0 or not sources):
                write_list(target,candidates,f"atomic:{category}/{name}"); current,state=candidates,"updated"
            else:
                current,state=previous,("kept_previous" if previous else "unavailable")
                if previous: write_list(target,previous,f"atomic:{category}/{name}:last-known-good")
            categories[category][name]=current
            statuses[f"{category}/{name}"]={"state":state,"rule_count":len(current),"previous_count":len(previous),"healthy_sources":healthy,"sources":results}

    compiled={}
    order=pcfg.get("category_order",list(categories)); rank={c:i for i,c in enumerate(order)}
    winners={}
    for category in order + [c for c in categories if c not in order]:
        if category not in categories: continue
        for rules in categories[category].values():
            for r in rules:
                if r not in winners or rank.get(category,999999) < rank.get(winners[r],999999): winners[r]=category
    for category,items in categories.items():
        kept=[r for rules in items.values() for r in rules if winners.get(r)==category]
        kept=list(dict.fromkeys(kept)); write_list(RULES/"compiled"/f"{category}.list",kept,f"compiled:{category}"); compiled[category]=len(kept)

    occ=defaultdict(set)
    for category,items in categories.items():
        for rules in items.values():
            for r in rules: occ[r].add(category)
    conflicts={r:sorted(c) for r,c in occ.items() if len(c)>1}
    resolved={r:{"winner":winners[r],"categories":sorted(c)} for r,c in occ.items() if len(c)>1}
    semantic=semantic_domain_redundancy(categories)
    semantic_counts=defaultdict(int)
    for finding in semantic: semantic_counts[finding["type"]]+=1
    REPORTS.mkdir(parents=True,exist_ok=True)
    report={"generated_at":now(),"status":statuses,"compiled_counts":compiled,"cross_category_conflicts":conflicts,"conflict_resolution":resolved,"semantic_redundancy":semantic,"semantic_redundancy_counts":dict(semantic_counts),"priority":pcfg}
    (REPORTS/"latest.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    md=["# Group-Rule 审计报告","",f"生成时间：`{report['generated_at']}`",f"跨分类重复规则：`{len(conflicts)}`",f"语义冗余：`{len(semantic)}`","", "## 分类统计",""]
    md += [f"- `{k}`：{v} 条" for k,v in compiled.items()]
    if semantic:
        md += ["","## 语义冗余审计","",f"发现 `{len(semantic)}` 条 DOMAIN / DOMAIN-SUFFIX 包含关系。当前**只审计、不自动删除**，避免误伤规则覆盖范围。",""]
        md += [f"- `{f['type']}`：`{f['covered']['rule']}` 可被 `{f['covering']['rule']}` 覆盖" for f in semantic[:100]]
    md += ["","## 原子规则状态",""]
    for key,st in sorted(statuses.items()):
        md.append(f"- `{key}`：**{st['state']}**，当前 {st['rule_count']}，历史 {st['previous_count']}，健康源 {st['healthy_sources']}")
        for src in st["sources"]:
            if src.get("status")!="ok": md.append(f"  - ⚠️ `{src.get('url')}` → `{src.get('status')}` {src.get('reason',src.get('error',''))}")
    if conflicts:
        md += ["","## 冲突处理","",f"共检测到 `{len(conflicts)}` 条跨分类重复规则；compiled 输出按 `priority.json` 自动保留优先级最高的分类。","", "## 冲突示例（最多 100 条）",""] + [f"- `{r}` → 胜出 `{winners[r]}`，涉及 {', '.join(c)}" for r,c in list(sorted(conflicts.items()))[:100]]
    (REPORTS/"latest.md").write_text("\n".join(md)+"\n",encoding="utf-8")
    print(json.dumps({"ok":True,"conflicts":len(conflicts),"semantic_redundancy":len(semantic),"compiled":compiled},ensure_ascii=False))

if __name__=="__main__": main()
