#!/usr/bin/env python3
"""Split TikTok-specific rules out of compiled/social.list.

The upstream TikTok source also contains shared ByteDance services (for example
CapCut/Trae). Only TikTok-owned rules are moved to the dedicated policy file;
shared/non-TikTok rules remain in social.list.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ATOMIC = ROOT / "rules" / "atomic" / "social" / "tiktok.list"
SOCIAL = ROOT / "rules" / "compiled" / "social.list"
TIKTOK = ROOT / "rules" / "compiled" / "tiktok.list"

EXACT_OR_SUFFIX_MARKERS = (
    "tiktok",
    "musical.ly",
)
SUPPORT_SUFFIXES = (
    "byteoversea.com",
    "bytedapm.com",
    "bytegecko-i18n.com",
    "byteintlapi.com",
    "ibytedtos.com",
    "ibyteimg.com",
    "ipstatp.com",
    "isnssdk.com",
    "muscdn.com",
    "sgpstatp.com",
    "snssdk.com",
    "tik-tokapi.com",
    "ttwebview.com",
)
SUPPORT_HOST_MARKERS = (
    "tiktokcdn",
    "tiktok-dm",
    "tiktok-web",
    "p16-sign",
    "p16-tiktok",
    "lf16-tiktok",
)


def is_tiktok_rule(rule: str) -> bool:
    kind, _, value = rule.partition(",")
    v = value.strip().lower()
    if kind == "USER-AGENT":
        return v.startswith("tiktok")
    if kind not in {"DOMAIN", "DOMAIN-SUFFIX", "DOMAIN-KEYWORD"}:
        return False
    if any(marker in v for marker in EXACT_OR_SUFFIX_MARKERS):
        return True
    if any(v == suffix or v.endswith("." + suffix) for suffix in SUPPORT_SUFFIXES):
        return True
    return any(marker in v for marker in SUPPORT_HOST_MARKERS)


def read_rules(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def write_generated(path: Path, rules: list[str], rule_type: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = [
        "# Generated by thunder0775/Group-Rule",
        f"# Type: {rule_type}",
        "# Policy intentionally omitted; assign policy in Shadowrocket .conf.",
        *rules,
        "",
    ]
    path.write_text("\n".join(body), encoding="utf-8")


def main() -> int:
    atomic_rules = read_rules(ATOMIC)
    social_rules = read_rules(SOCIAL)
    if not atomic_rules:
        raise SystemExit("TikTok atomic rule source is empty.")

    dedicated = list(dict.fromkeys(r for r in atomic_rules if is_tiktok_rule(r)))
    if not dedicated:
        raise SystemExit("No TikTok-specific rules were identified.")

    dedicated_set = set(dedicated)
    remaining = [r for r in social_rules if r not in dedicated_set]

    write_generated(TIKTOK, dedicated, "compiled:tiktok")
    write_generated(SOCIAL, remaining, "compiled:social:tiktok-split")

    print(f"TikTok dedicated rules: {len(dedicated)}")
    print(f"Remaining social rules: {len(remaining)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
