#!/usr/bin/env python3
"""Split the complete social/tiktok atomic rule set into a dedicated output."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ATOMIC = ROOT / "rules" / "atomic" / "social" / "tiktok.list"
SOCIAL = ROOT / "rules" / "compiled" / "social.list"
TIKTOK = ROOT / "rules" / "compiled" / "tiktok.list"


def read_rules(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def write_generated(path: Path, rules: list[str], rule_type: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = [
        "# Generated by thunder0775/Group-Rule",
        f"# Type: {rule_type}",
        "# Policy intentionally omitted; assign policy in Shadowrocket .conf.",
        *rules,
        "",
    ]
    path.write_text("\n".join(body), encoding="utf-8")


def main() -> int:
    # IMPORTANT: social/tiktok is a complete dedicated source.
    # Every rule in this atomic source, including CapCut/Trae/MarsCode and
    # other ByteDance-related domains, belongs to the dedicated network.
    atomic_rules = read_rules(ATOMIC)
    social_rules = read_rules(SOCIAL)
    if not atomic_rules:
        raise SystemExit("TikTok atomic rule source is empty.")

    dedicated = list(dict.fromkeys(atomic_rules))
    dedicated_set = set(dedicated)
    remaining = [r for r in social_rules if r not in dedicated_set]

    write_generated(TIKTOK, dedicated, "compiled:tiktok")
    write_generated(SOCIAL, remaining, "compiled:social:tiktok-split")

    print(f"TikTok dedicated rules: {len(dedicated)}")
    print(f"Remaining social rules: {len(remaining)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
